apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: production-key
    solvers:
      - http01:
          ingress:
            ingressClassName: {{ .Values.ingressClassName }}
            ingressTemplate:
              spec:
                rules:
                - http:
                    paths:
                    - path: /.well-known/acme-challenge
                      pathType: Prefix
