apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wg-easy.fullname" . }}
  labels:
    {{- include "wg-easy.labels" . | nindent 4 }}
type: Opaque
stringData:
  PASSWORD_HASH: {{ bcrypt .Values.PASSWORD }}
  {{- with .Values.env }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
