apiVersion: v1
kind: Service
metadata:
  name: {{ include "wg-easy.fullname" . }}
  labels:
    {{- include "wg-easy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.web.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.wireguard.port }}
      targetPort: wireguard
      protocol: UDP
      name: wireguard
  selector:
    {{- include "wg-easy.selectorLabels" . | nindent 4 }}
