apiVersion: v1
kind: Service
metadata:
  name: {{ include "snikket.fullname" . }}-turn-signaling
  labels:
    app: {{ include "snikket.name" . }}
    component: turn
spec:
  type: LoadBalancer
  ports:
    - name: stun-tcp-3478
      protocol: TCP
      port: 3478
      targetPort: stun-tcp-3478
    - name: stun-udp-3478
      protocol: UDP
      port: 3478
      targetPort: stun-udp-3478
    - name: stun-tcp-3479
      protocol: TCP
      port: 3479
      targetPort: stun-tcp-3479
    - name: stun-udp-3479
      protocol: UDP
      port: 3479
      targetPort: stun-udp-3479
    - name: stun-tls-tcp-5349
      protocol: TCP
      port: 5349
      targetPort: stun-tcp-5349
    - name: stun-tls-udp-5349
      protocol: UDP
      port: 5349
      targetPort: stun-udp-5349
    - name: stun-tls-tcp-5350
      protocol: TCP
      port: 5350
      targetPort: stun-tcp-5350
    - name: stun-tls-udp-5350
      protocol: UDP
      port: 5350
      targetPort: stun-udp-5350
  selector:
    app: {{ include "snikket.name" . }}
    component: server
