apiVersion: v1
kind: Secret
metadata:
  name: {{ include "code-server.fullname" . }}
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
type: Opaque
{{- with .Values.env }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
