apiVersion: v1
kind: Secret
metadata:
  name: {{ include "basic-auth.fullname" . }}
  labels:
    {{- include "basic-auth.labels" . | nindent 4 }}
type: Opaque
data:
  users:
    - {{ printf "%s:%s" .Values.username (htpasswd .Values.password | trim) | b64enc | quote }}
