apiVersion: v1
kind: Secret
metadata:
  name: {{ include "basic-auth.fullname" . }}
  labels:
    {{- include "basic-auth.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.username | b64enc | quote }}
  password: {{ .Values.password | b64enc | quote }}
